image: ocaml/opam2:latest

before_script:
  - sudo apt-get -y install m4 pkg-config libssl-dev libffi-dev
  - opam init
  - eval `opam config env`
  - opam update
  - opam pin add disml .

build:
  stage: build
  script:
  - opam pin add odoc --dev-repo
  only:
  - master

pages:
  stage: deploy
  script:
  - dune build @doc
  - cp -r _build/default/_doc/_html/ public/
  artifacts:
    paths:
    - public
  only:
  - tags